BEGIN;

CREATE TABLE IF NOT EXISTS authority_coordination_record (
    coordination_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_type varchar(30) NOT NULL,
    case_id varchar(30) NOT NULL,
    reference_no varchar(150) NOT NULL UNIQUE,
    authority_name varchar(200) NOT NULL,
    contact_person varchar(200),
    action_date date,
    coordination_status varchar(30) NOT NULL DEFAULT 'Pending',
    priority varchar(30) NOT NULL DEFAULT 'Normal',
    notes text,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_coordination_record_type
        CHECK (record_type IN ('Police Referral', 'Court Matter')),
    CONSTRAINT chk_coordination_status
        CHECK (coordination_status IN ('Pending', 'Scheduled', 'Submitted', 'Completed')),
    CONSTRAINT chk_coordination_priority
        CHECK (priority IN ('Normal', 'Urgent', 'Court Priority')),
    CONSTRAINT fk_coordination_case
        FOREIGN KEY (case_id) REFERENCES forensic_case(case_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_coordination_case
    ON authority_coordination_record(case_id);

CREATE INDEX IF NOT EXISTS idx_coordination_action_status
    ON authority_coordination_record(action_date, coordination_status);

COMMIT;
